// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:web:8af9bec1b6222a2901bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    authDomain: 'g-project-81290.firebaseapp.com',
    storageBucket: 'g-project-81290.firebasestorage.app',
    measurementId: 'G-WKTNKFEL2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_flPBvCF43wUw1n1WDFG30ko7xxqncZM',
    appId: '1:966277330376:android:14deed4a80ceb7eb01bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    storageBucket: 'g-project-81290.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:web:68b18830f4fb3d2801bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    authDomain: 'g-project-81290.firebaseapp.com',
    storageBucket: 'g-project-81290.firebasestorage.app',
    measurementId: 'G-MMF89HENX4',
  );
}
