// File generated by manual configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:web:8af9bec1b6222a2901bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    authDomain: 'g-project-81290.firebaseapp.com',
    storageBucket: 'g-project-81290.firebasestorage.app',
    measurementId: 'G-WKTNKFEL2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:android:cf3a0c5c3b9b4f6201bcfd', // Dummy fallback if needed, but actually web key works for Dart initialization
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    storageBucket: 'g-project-81290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:ios:cf3a0c5c3b9b4f6201bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    storageBucket: 'g-project-81290.firebasestorage.app',
    iosBundleId: 'com.example.gundamStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:ios:cf3a0c5c3b9b4f6201bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    storageBucket: 'g-project-81290.firebasestorage.app',
    iosBundleId: 'com.example.gundamStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHVIuCWKaaLdfVzyWeDJGiCHRt7WBeB4s',
    appId: '1:966277330376:web:8af9bec1b6222a2901bcfd',
    messagingSenderId: '966277330376',
    projectId: 'g-project-81290',
    authDomain: 'g-project-81290.firebaseapp.com',
    storageBucket: 'g-project-81290.firebasestorage.app',
    measurementId: 'G-WKTNKFEL2X',
  );
}
