name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: # Cho phép tự bấm chạy thủ công trên GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Lấy mã nguồn
        uses: actions/checkout@v4

      - name: Thiết lập Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Thiết lập Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Tải các thư viện (Pub get)
        run: flutter pub get

      - name: Build file APK
        run: flutter build apk --release

      - name: Đăng tải file APK lên Github
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
